# Generated by Django 5.0.7 on 2024-08-06 07:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wine',
            old_name='months',
            new_name='months_for_storage',
        ),
        migrations.AddField(
            model_name='wine',
            name='storage_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
