# Generated by Django 5.0.7 on 2024-08-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_months_wine_months_for_storage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='style',
            field=models.CharField(choices=[('Red', 'Red'), ('White', 'White')], default='Red', max_length=5),
        ),
    ]
