# Generated by Django 5.0.7 on 2024-08-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_wine_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='ready_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
